gfToken:
  cacheKey: "WechatGfToken:"
  timeOut: 2592000  #30天
  maxRefresh: 1296000
  multiLogin: true
  encryptKey: "49c54195e750b04e74a8429b17896586"
  cacheModel: "redis"
  excludePaths:
    - "/api/v1/wechat/login"
wechat:
  AppID: "wx54888472b36230aa"
  Secret: "0f805412db892087ffc5c5c2f2ae80a5"
  HttpDebug: false
  AesKey: "zUfVSOan3B5ZZZZZZ66ixY6OrB28MTS9OIiBLaq3q2PhNG"
  isDebug: true
  isDebug2: true
  Log:
    Level: "debug"
    File: "./resource/log/wechat/wechat.log"
    Error: "./resource/log/wechat/error.log"
  Cache:
    Type: 1 #0使用内存 1使用redis
    Addr: "127.0.0.1:6379"
    Password: ""
    DB: 0