// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"fanzhou-go/internal/app/fanzhouApi/dao/internal"
)

// taskDao is the data access object for the table task.
// You can define custom methods on it to extend its functionality as needed.
type taskDao struct {
	*internal.TaskDao
}

var (
	// Task is a globally accessible object for table task operations.
	Task = taskDao{internal.NewTaskDao()}
)

// Add your custom methods and functionality below.
