// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fanzhou-go/internal/app/system/dao/internal"
)

// internalBigFileDao is internal type for wrapping internal DAO implements.
type internalBigFileDao = *internal.BigFileDao

// bigFileDao is the data access object for table big_file.
// You can define custom methods on it to extend its functionality as you wish.
type bigFileDao struct {
	internalBigFileDao
}

var (
	// BigFile is globally public accessible object for table big_file operations.
	BigFile = bigFileDao{
		internal.NewBigFileDao(),
	}
)

// Fill with you ideas below.
