// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"fanzhou-go/internal/app/system/dao/internal"
)

// userLoginLogDao is the data access object for the table user_login_log.
// You can define custom methods on it to extend its functionality as needed.
type userLoginLogDao struct {
	*internal.UserLoginLogDao
}

var (
	// UserLoginLog is a globally accessible object for table user_login_log operations.
	UserLoginLog = userLoginLogDao{internal.NewUserLoginLogDao()}
)

// Add your custom methods and functionality below.
