// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BigFile is the golang structure of table big_file for DAO operations like Where/Data.
type BigFile struct {
	g.Meta    `orm:"table:big_file, do:true"`
	Id        interface{} //
	Name      interface{} // 文件名称
	Size      interface{} // 文件大小
	Path      interface{} // 文件相对路径
	FullPath  interface{} // 文件绝对路径
	MimeType  interface{} // 文件类型
	Source    interface{} // 文件来源  0 - 本地，1 - 腾讯云 2 - 七牛云
	Describe  interface{} // 描述
	Md5       interface{} // md5
	CreatedBy interface{} //
	UpdatedBy interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
	DeletedAt *gtime.Time //
}
