// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "fanzhou-go/internal/logic/bizctx"
	_ "fanzhou-go/internal/logic/middleware"
	_ "fanzhou-go/internal/logic/session"
	_ "fanzhou-go/internal/logic/user"
)
