# CLI.
gfcli:
  gen:
    dao:
      - link:            "mysql:root:@tcp(127.0.0.1:3306)/test"
        tables:          "user_login_log"
        removePrefix:    "gf_"
        descriptionTag:  true
        noModelComment:  true
        path: "./internal/app/fanzhouApi"
      - link: "mysql:root:@tcp(127.0.0.1:3306)/test"
        tables: "user"
        removePrefix: "gf_"
        descriptionTag: true
        noModelComment: true
        path: "./internal/app/fanzhouApi"
      - link: "mysql:root:@tcp(127.0.0.1:3306)/test"
        tables: "task"
        removePrefix: "gf_"
        descriptionTag: true
        noModelComment: true
        path: "./internal/app/fanzhouApi"