// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "fanzhou-go/internal/app/common/logic/bigUpload"
	_ "fanzhou-go/internal/app/common/logic/cache"
	_ "fanzhou-go/internal/app/common/logic/captcha"
	_ "fanzhou-go/internal/app/common/logic/eventBus"
	_ "fanzhou-go/internal/app/common/logic/middleware"
	_ "fanzhou-go/internal/app/common/logic/snowIDGen"
	_ "fanzhou-go/internal/app/common/logic/sysConfig"
	_ "fanzhou-go/internal/app/common/logic/sysDictData"
	_ "fanzhou-go/internal/app/common/logic/sysDictType"
	_ "fanzhou-go/internal/app/common/logic/upload"
)
