// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"fanzhou-go/api/v1/system"
)

type IBigUpload interface {
	Upload(ctx context.Context, req *system.BigUploadReq) (res *system.BigUploadRes, err error)
	UploadCheck(ctx context.Context, req *system.BigUploadCheckReq) (res *system.BigUploadCheckRes, err error)
	UploadMerge(ctx context.Context, req *system.BigUploadMergeReq) (res *system.BigUploadRes, err error)
}

var localBigUpload IBigUpload

func BigUpload() IBigUpload {
	if localBigUpload == nil {
		panic("implement not found for interface IBigUpload, forgot register?")
	}
	return localBigUpload
}

func RegisterBigUpload(i IBigUpload) {
	localBigUpload = i
}
